name: Build Compose for Desktop App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest  # Linux build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build all Linux packages (Deb, Rpm, AppImage)
        run: ./gradlew packageDistributionForCurrentOS

      - name: Upload Linux builds (AppImage, Deb, Rpm)
        uses: actions/upload-artifact@v4
        with:
          name: Linux-Builds
          path: build/compose/binaries/main/app/*

  windows-build:
    runs-on: windows-latest  # Windows build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Windows MSI
        run: ./gradlew packageDistributionForCurrentOS

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build
          path: build/compose/binaries/main/msi/*

  macos-build:
    runs-on: macos-latest  # macOS build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build macOS DMG
        run: ./gradlew packageDistributionForCurrentOS
        
      - name: Upload macOS build
        uses: actions/upload-artifact@v4
        with:
          name: MacOS-Build
          path: build/compose/binaries/main/dmg/*

  release:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Linux Builds
        uses: actions/download-artifact@v4
        with:
          name: Linux-Builds
          path: linux/

      - name: Download Windows Builds
        uses: actions/download-artifact@v4
        with:
          name: Windows-Build
          path: windows/

      - name: Download macOS Builds
        uses: actions/download-artifact@v4
        with:
          name: MacOS-Build
          path: macos/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0  # Change this for new versions
          name: "Ollama v1.0.0"
          body: "Automated release of Ollama app."
          draft: false
          prerelease: false
          files: |
            linux/*
            windows/*
            macos/*
